### ISSUE TITLE
Installation fails on an Ubuntu Cosmic system

### ISSUE THREAD

**Issue by snesbittsea** [m4rcu5nl/ansible-role-zerotier#26]
On a Cosmic Cuttlefish system, role will fail when trying to install the deb package from ZerotierOne.

The core problem is the "Add ZerotTier APT repository" task which generates the repository string based on the ansible_distribution_release variable. Zerotier does not provide a repository for cosmic. (I'm guessing Zerotier will only provide repos for LTS releases),

I worked around the issue by  adding a new variable - zerotier_apt_repo - which then permits one to override the generated value.

I'd be happy to submit my changes - including doc updates - as a patch or pull request if this solution is acceptable.

**Comment by m4rcu5nl** [comment]
Thanks! Good catch. Weird though, since ZeroTier has provided non-LTS release repos in the past. 

I like your workaround and tried expanding on it a little to eliminate the need to manually override the variable. Could you take a look at commit fd68894 in the develop branch and let me know if that would work for you?

**Comment by snesbittsea** [comment]
Thanks - that will work!

**Comment by colbin8r** [comment]
@m4rcu5nl I think this is an issue again on Ubuntu 20.04.1 LTS. I get a similar error:

```
TASK [m4rcu5nl.zerotier-one : Overwrite Ubuntu release repo name] **************************************************************************************************************************************************************************
skipping: [...]

TASK [m4rcu5nl.zerotier-one : Re-gather facts] *********************************************************************************************************************************************************************************************
skipping: [...]

TASK [m4rcu5nl.zerotier-one : Add ZeroTier APT repository] *********************************************************************************************************************************************************************************
fatal: [...]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://download.zerotier.com/debian/focal focal Release' does not have a Release file."}
```

**Comment by snesbittsea** [comment]
Hi Colby:



Zerotier doesn't have a focal repository. I've been using the bionic repo on focal and gorilla.



-steve


---- On Fri, 20 Nov 2020 11:38:48 -0800 Colby Rogness <notifications@github.com> wrote ----




https://github.com/m4rcu5nl I think this is an issue again on Ubuntu 20.04.1 LTS. I get a similar error:

TASK [m4rcu5nl.zerotier-one : Overwrite Ubuntu release repo name] **************************************************************************************************************************************************************************
skipping: [...]

TASK [m4rcu5nl.zerotier-one : Re-gather facts] *********************************************************************************************************************************************************************************************
skipping: [...]

TASK [m4rcu5nl.zerotier-one : Add ZeroTier APT repository] *********************************************************************************************************************************************************************************
fatal: [...]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://download.zerotier.com/debian/focal focal Release' does not have a Release file."}
