### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by theronic** [m4rcu5nl/ansible-role-zerotier#27]
Hi, I'm trying to use this, but I don't know how. Where do I put "m4rcu5nl.zerotier"? I don't see a role named zerotier or a file name zerotier.yml.

**Comment by m4rcu5nl** [comment]
Hi. I see I made a typo in the readme file. When you download the role via Ansible Galaxy it will be called "m4rcu5nl.zerotier-one" instead. I will fix the readme. Sorry about that.

If you did not use Ansible Galaxy to download the role it will most likely be in a folder called "ansible-role-zerotier" Make sure you store that folder in a place where you configured Ansible to look for roles so you can call it from your playbooks by the name "ansible-role-zerotier"

I hope this answered your question. If it didn't, feel free to reopen the issue.

**Comment by theronic** [comment]
Thanks :) I figured out that that name refers to the folder relative to `roles` path where ansible-playbook is called.
